[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "blockviz-backend"               # package import name stays "backend"
version = "0.1.0"

[tool.setuptools.packages.find]
include = ["*"]
