name: prices-candles

on:
  workflow_dispatch:
    inputs:
      run_03: { description: "03_create_hourly_from_10m.py", required: false, default: "true" }
      run_04: { description: "04_create_daily_from_10m.py", required: false, default: "true" }
      TOP_N:  { description: "Override TOP_N", required: false, default: "" }
      VERBOSE_MODE: { description: "Verbose (0/1)", required: false, default: "0" }

permissions:
  contents: read

concurrency:
  group: prices-candles-${{ github.ref }}
  cancel-in-progress: false   # let a candle run finish

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      TZ: UTC
      PYTHONUNBUFFERED: "1"
      PYTHONUTF8: "1"
      PYTHONWARNINGS: default
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "prices/requirements.txt"  # <-- updated

      - name: Install deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install "cassandra-driver==3.29.0" requests python-dotenv tzdata
          # If you keep extra pins in prices/requirements.txt, uncomment:
          # pip install -r prices/requirements.txt

      - name: Astra bundle
        run: |
          echo "${{ secrets.ASTRA_BUNDLE_BASE64 }}" | base64 -d > secure-connect.zip
          test -s secure-connect.zip

      - name: 03 Update hourly from 10m
        if: ${{ github.event.inputs.run_03 == 'true' }}
        timeout-minutes: 12
        env:
          ASTRA_BUNDLE_PATH: secure-connect.zip
          ASTRA_TOKEN: ${{ secrets.ASTRA_TOKEN }}
          ASTRA_KEYSPACE: ${{ secrets.ASTRA_KEYSPACE }}
          TOP_N: ${{ github.event.inputs.TOP_N != '' && github.event.inputs.TOP_N || secrets.TOP_N || '200' }}
          REQUEST_TIMEOUT_SEC: "40"
          CONNECT_TIMEOUT_SEC: "15"
          FETCH_SIZE: "500"
          SLOT_DELAY_SEC: "120"
          CURRENT_ONLY: "1"            # prev + current hour
          FINALIZE_PREV: "1"
          PROGRESS_EVERY: "20"
          VERBOSE_MODE: ${{ github.event.inputs.VERBOSE_MODE || '0' }}
        run: python prices/03_create_hourly_from_10m.py   # <-- updated

      - name: 04 Update/close daily from 10m
        if: ${{ github.event.inputs.run_04 == 'true' }}
        timeout-minutes: 12
        env:
          ASTRA_BUNDLE_PATH: secure-connect.zip
          ASTRA_TOKEN: ${{ secrets.ASTRA_TOKEN }}
          ASTRA_KEYSPACE: ${{ secrets.ASTRA_KEYSPACE }}
          TOP_N: ${{ github.event.inputs.TOP_N != '' && github.event.inputs.TOP_N || secrets.TOP_N || '200' }}
          REQUEST_TIMEOUT_SEC: "40"
          CONNECT_TIMEOUT_SEC: "15"
          FETCH_SIZE: "500"
          SLOT_DELAY_SEC: "120"
          PROGRESS_EVERY: "20"
          VERBOSE_MODE: ${{ github.event.inputs.VERBOSE_MODE || '0' }}
        run: python prices/04_create_daily_from_10m.py     # <-- updated
