name: dq-repair-full
on:
  schedule:
    - cron: "10 4 1 * *" # 04:10 UTC on the 1st each month
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          {
            python-version: "3.11",
            cache: "pip",
            cache-dependency-path: "requirements.txt",
          }
      - run: |
          python -m pip install --upgrade pip
          pip install "cassandra-driver==3.29.0" requests python-dotenv tzdata
      - run: echo "PYTHONPATH=." >> "$GITHUB_ENV"
      - run: echo "${{ secrets.ASTRA_BUNDLE_BASE64 }}" | base64 -d > secure-connect.zip
      - name: Run full repair
        env:
          ASTRA_BUNDLE_PATH: secure-connect.zip
          ASTRA_TOKEN: ${{ secrets.ASTRA_TOKEN }}
          ASTRA_KEYSPACE: ${{ secrets.ASTRA_KEYSPACE }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          COINGECKO_API_TIER: ${{ secrets.COINGECKO_API_TIER != '' && secrets.COINGECKO_API_TIER || 'pro' }}

          FULL_MODE: "1"
          TRUNCATE_AGGREGATES_IN_FULL: "1"
          FULL_DAILY_ALL: "1"
          DQ_VERBOSE: "1"
        run: python prices/FF_gck_dq_repair_timeseries.py
