name: prices-realtime

on:
  workflow_dispatch:
    inputs:
      run_01: { description: "01_load_prices_live.py", required: false, default: "true" }
      run_02: { description: "02_append_10m_from_live.py", required: false, default: "true" }
      TOP_N:  { description: "Override TOP_N", required: false, default: "" }
      VERBOSE_MODE: { description: "Verbose (0/1)", required: false, default: "0" }

permissions:
  contents: read

concurrency:
  group: prices-realtime-${{ github.ref }}
  cancel-in-progress: true   # fast loop can be pre-empted

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TZ: UTC
      PYTHONUNBUFFERED: "1"
      PYTHONUTF8: "1"
      PYTHONWARNINGS: default
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip", cache-dependency-path: "requirements.txt" }
      - name: Install deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install "cassandra-driver==3.29.0" requests python-dotenv tzdata
      - name: Astra bundle
        run: |
          echo "${{ secrets.ASTRA_BUNDLE_BASE64 }}" | base64 -d > secure-connect.zip
          test -s secure-connect.zip
      - name: 01 Load prices_live_rolling
        if: ${{ github.event.inputs.run_01 == 'true' }}
        timeout-minutes: 8
        env:
          ASTRA_BUNDLE_PATH: secure-connect.zip
          ASTRA_TOKEN: ${{ secrets.ASTRA_TOKEN }}
          ASTRA_KEYSPACE: ${{ secrets.ASTRA_KEYSPACE }}
          TOP_N: ${{ github.event.inputs.TOP_N != '' && github.event.inputs.TOP_N || secrets.TOP_N || '200' }}
          RETRIES: "3"
          BACKOFF_MIN: "5"
          MAX_BACKOFF_MIN: "30"
          REQUEST_TIMEOUT_SEC: "60"
          CONNECT_TIMEOUT_SEC: "15"
          FETCH_SIZE: "500"
          BATCH_FLUSH_EVERY: "40"
          RUN_FOREVER: "0"
          WAIT_STALE_SEC: "60"
          VERBOSE_MODE: ${{ github.event.inputs.VERBOSE_MODE || '0' }}
        run: python 01_load_prices_live.py
      - name: 02 Append 10m from live_rolling
        if: ${{ github.event.inputs.run_02 == 'true' }}
        timeout-minutes: 7
        env:
          ASTRA_BUNDLE_PATH: secure-connect.zip
          ASTRA_TOKEN: ${{ secrets.ASTRA_TOKEN }}
          ASTRA_KEYSPACE: ${{ secrets.ASTRA_KEYSPACE }}
          TOP_N: ${{ github.event.inputs.TOP_N != '' && github.event.inputs.TOP_N || secrets.TOP_N || '200' }}
          REQUEST_TIMEOUT_SEC: "60"
          CONNECT_TIMEOUT_SEC: "15"
          FETCH_SIZE: "500"
          SLOT_DELAY_SEC: "120"
          SLOTS_BACKFILL: "2"        # current + previous slot
          VERBOSE_MODE: ${{ github.event.inputs.VERBOSE_MODE || '0' }}
        run: python 02_append_10m_from_live.py
